export { default as Navbar } from "./Navbar/Navbar";
export { default as Footer } from "./Footer/Footer";
export { default as InfoSection } from "./InfoSection/InfoSection";
export { default as IntroSection } from "./IntroSection/Intro";
export { default as WorkSection } from "./Work/Work";
export { default as EducationSection } from "./Education/Education";
export { default as MoocSection } from "./Mooc/Mooc";
export { default as ProjectSection } from "./Projects/Projects";
export { default as Pricing } from "./Pricing/Pricing";
